require:
  - standard

plugins:
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - vendor/**/*
    - tmp/**/*

Minitest:
  Enabled: true

Performance:
  Enabled: true
